#Specify the base image
FROM node:16

#Set the working directory
WORKDIR /app

#Copy the package.json file to the working directory
COPY package*.json ./

#Install the dependencies
RUN npm install

#Copy the rest of the files to the working directory
COPY . .

#Expose the port
EXPOSE 4000

#Run the app
CMD ["node", "app.js"]
